In [ ]:
import sys
import cv2 as cv
import numpy as np
#  Global Variables
DELAY_CAPTION = 1500
DELAY_BLUR = 100
MAX_KERNEL_LENGTH = 31
src = None
dst = None
window_name = 'Smoothing Demo'
def main(argv):
    cv.namedWindow(window_name, cv.WINDOW_AUTOSIZE)
    # Load the source image
    global src
    image_path = r'C:\Users\Dylan Sy\Desktop\biomed\ISCS_30.65\Gaussian\noisy.png'
    src = cv.imread(image_path)
    print(src)
    if src is None:
        print(f'Error opening image at path: {image_path}')
        return -1
    if display_caption('Original Image') != 0:
        return 0
    global dst
    dst = np.copy(src)
    if display_dst(DELAY_CAPTION) != 0:
        return 0
    # Applying Gaussian blur
    if display_caption('Gaussian Blur') != 0:
        return 0
    
    for i in range(1, MAX_KERNEL_LENGTH, 2):
        dst = cv.GaussianBlur(src, (i, i), -1)
        if display_dst(DELAY_BLUR) != 0:
            return 0
    cv.imshow('Denoised Image', dst)
    cv.waitKey(0)
    cv.destroyAllWindows()

# Save the denoised image to a file
    output_path = r'C:\Users\Dylan Sy\Desktop\biomed\ISCS_30.65\Gaussian\gaussian.png'  # Replace with your desired output path
    cv.imwrite(output_path, dst)
    print("Denoised image saved to " + output_path)
def display_caption(caption):
    global dst
    dst = np.zeros(src.shape, src.dtype)
    rows, cols, _ch = src.shape
    cv.putText(dst, caption,
                (int(cols / 4), int(rows / 2)),
                cv.FONT_HERSHEY_COMPLEX, 1, (255, 255, 255))
    return display_dst(DELAY_CAPTION)
def display_dst(delay):
    cv.imshow(window_name, dst)
    c = cv.waitKey(delay)
    if c >= 0 : return -1
    return 0
def calculate_psnr(original, denoised):
    mse = np.mean((original - denoised) ** 2)
    max_pixel_value = 255.0  # Assuming 8-bit images

    psnr = 10 * np.log10((max_pixel_value ** 2) / mse)
    return psnr

# Example usage:
clear =  r'C:\Users\Dylan Sy\Desktop\biomed\ISCS_30.65\Gaussian\clear.png'
gaussian =  r'C:\Users\Dylan Sy\Desktop\biomed\ISCS_30.65\Gaussian\gaussian.png'
clear_image = cv.imread(clear)
processed_image = cv.imread(gaussian)

psnr_score = calculate_psnr(clear_image, processed_image)
print(f"PSNR Score: {psnr_score} dB")
if __name__ == "__main__":
    main(sys.argv[1:])

PSNR Score: 28.242578365352106 dB
[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]]


error: OpenCV(4.9.0) :-1: error: (-5:Bad argument) in function 'GaussianBlur'
> Overload resolution failed:
>  - Can't parse 'ksize'. Input argument doesn't provide sequence protocol
>  - Can't parse 'ksize'. Input argument doesn't provide sequence protocol
